name: Feature request
description: Suggest an improvement or new capability for Gemini Launcher.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing ideas to make Gemini Launcher better! Share as much detail as you can so we can evaluate and prioritize the request.
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the pain point or workflow that would benefit from this change.
      placeholder: |
        - Who is impacted?
        - What is the current limitation?
        - Why is a change needed?
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Explain how you would like the feature to work.
      placeholder: |
        - Describe the desired behavior
        - Include UI/UX considerations if relevant
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any workarounds or other approaches you have evaluated.
      placeholder: |
        - Alternative 1
        - Alternative 2
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add screenshots, references, or other context to help us understand the request.
