name: Question
description: Ask a question about using or configuring Codex Launcher.
title: "[Question]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Share details so the community can help quickly.
  - type: input
    id: summary
    attributes:
      label: Question summary
      description: Provide a short headline for your question.
      placeholder: e.g. How do I point Codex Launcher to a custom Codex CLI binary?
    validations:
      required: true
  - type: textarea
    id: question_details
    attributes:
      label: Details
      description: Include the full question, context, and what you've tried so far.
      placeholder: |
        - What are you trying to achieve?
        - What steps have you taken?
        - Any error messages or unexpected behavior?
    validations:
      required: true
  - type: dropdown
    id: topic
    attributes:
      label: Topic (optional)
      description: Select the area your question relates to.
      options:
        - label: Select topic…
          value: ""
        - label: Getting started / setup
          value: setup
        - label: Configuration & settings
          value: configuration
        - label: Codex CLI integration
          value: cli
        - label: IDE workflow
          value: ide
        - label: Other
          value: other
  - type: input
    id: codex_cli_version
    attributes:
      label: Codex CLI version
      description: Which Codex CLI version are you using?
      placeholder: e.g. 0.36.0
  - type: input
    id: plugin_version
    attributes:
      label: Codex Launcher version (optional)
      placeholder: e.g. 1.0.12
  - type: input
    id: ide_version
    attributes:
      label: IDE version (optional)
      placeholder: e.g. IntelliJ IDEA 2024.2 (Build 242.10180.27)
