name: Question
description: Ask a question about using or configuring Gemini Launcher.
title: "[Question]: "
labels:
  - question
  - request ai review
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Share details so the community can help quickly.
  - type: checkboxes
    id: launcher_focus
    attributes:
      label: Confirm question scope
      options:
        - label: I confirm this question is about Gemini Launcher, not Gemini CLI.
          required: true
  - type: textarea
    id: question_details
    attributes:
      label: Details
      description: Include the full question, context, and what you've tried so far.
      placeholder: |
        - What are you trying to achieve?
        - What steps have you taken?
        - Any error messages or unexpected behavior?
    validations:
      required: true
  - type: input
    id: gemini_cli_version
    attributes:
      label: Gemini CLI version
      description: Which Gemini CLI version are you using?
      placeholder: e.g. 0.4x.y
  - type: dropdown
    id: shell
    attributes:
      label: Shell configured in JetBrains IDE
      description: Choose the same shell configured in your JetBrains IDE terminal (Settings > Tools > Terminal > Application Settings > Shell Path). If you pick Other, add details in the description above.
      options:
        - zsh
        - bash
        - fish
        - PowerShell (>= 7.3)
        - PowerShell (< 7.3)
        - Other
  - type: input
    id: plugin_version
    attributes:
      label: Gemini Launcher version
      placeholder: e.g. 1.x.y
  - type: input
    id: ide_version
    attributes:
      label: IDE version
      placeholder: e.g. IntelliJ IDEA 2024.2 (Build 242.10180.27)
